export { default as About } from "./About/About.jsx"
export { default as Footer } from "./Footer/Footer.tsx"
export { default as Header } from "./Header/Header.tsx"
export { default as Skills } from "./Skills/Skills.jsx"
export { default as Testimonial } from "./Testimonial/Testimonial.jsx"
export { default as Work } from "./Work/Work.jsx"